"""
Flickzy transactional email service using Brevo REST API.

Brevo sends:
- Email verification OTP
- Password reset OTP
- Password changed notification
"""

import html
import json
import os
import urllib.error
import urllib.request


BREVO_API_KEY = os.getenv("BREVO_API_KEY", "").strip()
BREVO_SENDER_EMAIL = os.getenv("BREVO_SENDER_EMAIL", "").strip()
BREVO_SENDER_NAME = os.getenv("BREVO_SENDER_NAME", "Flickzy").strip()

BREVO_API_URL = "https://api.brevo.com/v3/smtp/email"


def is_brevo_configured() -> bool:
    return bool(
        BREVO_API_KEY
        and BREVO_SENDER_EMAIL
    )


def _extract_otp(body: str) -> str:
    """
    Extract a 6-digit OTP from the email body.

    This keeps OTP generation completely inside auth.py.
    The email service only finds the existing OTP and displays it.
    """

    import re

    match = re.search(r"\b(\d{6})\b", body)

    if match:
        return match.group(1)

    return ""


def _build_html_email(
    to_email: str,
    subject: str,
    body: str,
) -> str:
    """
    Build the HTML email template for Flickzy.

    OTP is extracted from the existing body generated by auth.py.
    Authentication and OTP verification remain unchanged.
    """

    otp = _extract_otp(body)

    safe_subject = html.escape(subject)
    safe_body = html.escape(body)

    # Remove the OTP from the normal message so it isn't displayed twice.
    if otp:
        safe_body = safe_body.replace(otp, "", 1)

    # Clean up common punctuation left after removing OTP.
    safe_body = safe_body.replace("  ", " ").strip()

    # Convert newlines to HTML line breaks.
    safe_body = safe_body.replace("\n", "<br>")

    otp_section = ""

    if otp:
        otp_section = f"""
        <div style="
            margin: 28px 0;
            text-align: center;
        ">
            <div style="
                display: inline-block;
                background: #f7f7f7;
                border: 1px solid #e6e6e6;
                border-radius: 14px;
                padding: 18px 28px;
            ">
                <div style="
                    font-size: 12px;
                    font-weight: 600;
                    color: #777777;
                    letter-spacing: 1.5px;
                    text-transform: uppercase;
                    margin-bottom: 8px;
                ">
                    Your verification code
                </div>

                <div style="
                    font-size: 34px;
                    line-height: 1.2;
                    font-weight: 700;
                    letter-spacing: 8px;
                    color: #171717;
                    font-family: Arial, Helvetica, sans-serif;
                ">
                    {otp}
                </div>
            </div>
        </div>
        """

    return f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0">

    <title>{safe_subject}</title>
</head>

<body style="
    margin: 0;
    padding: 0;
    background-color: #f4f4f5;
    font-family: Arial, Helvetica, sans-serif;
    color: #171717;
">

    <div style="
        width: 100%;
        padding: 40px 16px;
        box-sizing: border-box;
    ">

        <div style="
            max-width: 520px;
            margin: 0 auto;
            background-color: #ffffff;
            border-radius: 20px;
            overflow: hidden;
            border: 1px solid #e8e8e8;
        ">

            <!-- Header -->
            <div style="
                padding: 28px 30px;
                text-align: center;
                border-bottom: 1px solid #eeeeee;
            ">

                <div style="
                    font-size: 30px;
                    font-weight: 800;
                    letter-spacing: -1px;
                    color: #171717;
                ">
                    Flickzy
                </div>

                <div style="
                    margin-top: 6px;
                    font-size: 12px;
                    color: #888888;
                    letter-spacing: 1px;
                ">
                    CONNECT • CREATE • FLICK
                </div>

            </div>


            <!-- Main Content -->
            <div style="
                padding: 34px 30px 30px;
            ">

                <div style="
                    font-size: 13px;
                    color: #888888;
                    margin-bottom: 10px;
                ">
                    FLICKZY
                </div>

                <h1 style="
                    margin: 0 0 16px;
                    font-size: 25px;
                    line-height: 1.3;
                    color: #171717;
                    font-weight: 700;
                ">
                    {safe_subject}
                </h1>

                <p style="
                    margin: 0;
                    font-size: 15px;
                    line-height: 1.7;
                    color: #555555;
                ">
                    {safe_body}
                </p>


                {otp_section}


                <!-- Expiry -->
                <div style="
                    margin-top: 20px;
                    padding: 14px 16px;
                    background-color: #fafafa;
                    border-radius: 10px;
                    border: 1px solid #eeeeee;
                ">

                    <p style="
                        margin: 0;
                        font-size: 13px;
                        line-height: 1.6;
                        color: #777777;
                    ">
                        ⏱️ This code expires in
                        <strong style="color: #555555;">
                            30 minutes
                        </strong>.
                    </p>

                </div>


                <!-- Security -->
                <p style="
                    margin: 24px 0 0;
                    font-size: 12px;
                    line-height: 1.6;
                    color: #999999;
                ">
                    🛡️ If you didn't request this email,
                    you can safely ignore it. Never share your
                    verification code with anyone.
                </p>

            </div>


            <!-- Footer -->
            <div style="
                padding: 22px 30px;
                background-color: #fafafa;
                border-top: 1px solid #eeeeee;
                text-align: center;
            ">

                <p style="
                    margin: 0 0 6px;
                    font-size: 13px;
                    color: #777777;
                ">
                    — Flickzy Team
                </p>

                <p style="
                    margin: 0;
                    font-size: 11px;
                    color: #aaaaaa;
                ">
                    This is an automated email.
                    Please do not reply.
                </p>

            </div>

        </div>


        <!-- Bottom text -->
        <div style="
            max-width: 520px;
            margin: 18px auto 0;
            text-align: center;
        ">

            <p style="
                margin: 0;
                font-size: 11px;
                line-height: 1.5;
                color: #999999;
            ">
                © Flickzy. All rights reserved.
            </p>

        </div>

    </div>

</body>
</html>
"""


def send_email(to_email: str, subject: str, body: str) -> bool:
    """
    Send a transactional email through Brevo.

    Returns:
        True  -> Brevo accepted the email
        False -> email was not sent

    Authentication, OTP generation, OTP storage and OTP verification
    remain completely inside Flickzy.
    """

    if not is_brevo_configured():
        print(
            "[Flickzy email] Brevo is not configured.\n"
            f"To: {to_email}\n"
            f"Subject: {subject}\n"
            f"Body: {body}\n",
            flush=True,
        )
        return False

    html_content = _build_html_email(
        to_email=to_email,
        subject=subject,
        body=body,
    )

    payload = {
        "sender": {
            "name": BREVO_SENDER_NAME,
            "email": BREVO_SENDER_EMAIL,
        },
        "to": [
            {
                "email": to_email,
            }
        ],
        "subject": subject,
        "htmlContent": html_content,
        "textContent": body,
    }

    request = urllib.request.Request(
        BREVO_API_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "accept": "application/json",
            "api-key": BREVO_API_KEY,
            "content-type": "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(request, timeout=15) as response:
            response_body = response.read().decode("utf-8")

        print(
            f"[Flickzy email] Brevo accepted email to {to_email}: "
            f"{response_body}",
            flush=True,
        )

        return True

    except urllib.error.HTTPError as error:
        error_body = error.read().decode(
            "utf-8",
            errors="replace",
        )

        print(
            f"[Flickzy email] Brevo HTTP {error.code}: "
            f"{error_body}",
            flush=True,
        )

        return False

    except Exception as error:
        print(
            f"[Flickzy email] Failed to send to {to_email}: "
            f"{error}",
            flush=True,
        )

        return False